# Generated by Django 3.2.7 on 2021-09-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productdetails_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='stk_upto',
            field=models.DateTimeField(null=True),
        ),
    ]
