# Generated by Django 3.2.7 on 2021-09-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='is_empty',
            field=models.BooleanField(null=True),
        ),
    ]
