# Generated by Django 3.2.7 on 2021-09-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210923_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_checkout',
            field=models.BooleanField(null=True),
        ),
    ]
